add 'sum' function

In [2]:
# sum


import numpy as np

x = np.array([[1,2,3],[4,5,6]])
y = np.reshape(x, (6,))
print(y)

[1 2 3 4 5 6]


In [2]:
class Sum(Function):
    def forward(self, x):
        self.x_shape = x.shape
        y = x.sum()
        return y

    def backward(self, gy):
        gx = broadcase_to(gy, self.x_shape)
        return gx

def sum(x):
    return Sum()(x)

NameError: name 'Function' is not defined

In [6]:
import sys
import os

cwd = os.getcwd()
parent_dir = os.path.abspath(os.path.join(cwd, os.pardir))
sys.path.append(parent_dir)

import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array([1,2,3,4,5,6]))
y = F.sum(x)
y.backward()

print(y)
print(x.grad)



variable(21)
variable([1 1 1 1 1 1])


In [8]:
x = Variable(np.array([[1,2,3],[4,5,6]]))
y = F.sum(x)
y.backward()

print(y)
print(x.grad)

variable(21)
variable([[1 1 1]
          [1 1 1]])


In [10]:
# axis, keepdims

class Sum(Function):
    def __init__(self, axis, keepdims):
        self.axis = axis
        self.keepdims = keepdims
    
    def forward(self, x):
        self.x_shape = x.shape
        y = x.sum(axis=self.axis, keepdims=self.keepdims)
        return y

    def backward(self, gy):
        gy = utils.reshape_sum_backward(gy, self.x_shape, self.axis, self.keepdims)
        
        gx = broadcase_to(gy, self.x_shape)
        return gx

def sum(x, axis=None, keepdims=False):
    return Sum(axis, keepdims)(x)

NameError: name 'Function' is not defined

In [14]:
x = Variable(np.array([[1,2,3],[4,5,6]]))
y = F.sum(x, axis=0)
y.backward()

print(y)
print(x.grad)

x = Variable(np.random.randn(2, 3, 4, 5))
y = x.sum(keepdims=True)
print(y.shape)


variable([5 7 9])
variable([[1 1 1]
          [1 1 1]])
(1, 1, 1, 1)
