Implement two functions (reshape, transpose)
They do not operate element by element

In [2]:
# reshape

import numpy as np

x = np.array([[1,2,3],[4,5,6]])
y = np.reshape(x, (6,))
print(y)

[1 2 3 4 5 6]


In [4]:
# to make backprop work, shape of x == shape of x.grad

class Reshape(Function):
    def __init__(self, shape):
        self.shape = shape

    def forward(self, x):
        self.x_shape = x.shape
        y = x.reshape(self.shape)
        return y

    def backward(self, gy):
        return reshape(gy, self.x_shape)

NameError: name 'Function' is not defined

In [8]:


import sys
import os

cwd = os.getcwd()
parent_dir = os.path.abspath(os.path.join(cwd, os.pardir))
sys.path.append(parent_dir)

from dezero.core import as_variable

def reshape(x, shape):
    if x.shape == shape:
        return as_variable(x)
    return Reshape(shape)(x)



In [12]:
import numpy as np
from dezero import Variable
import dezero.functions as F

x = Variable(np.array([[1,2,3], [4,5,6]]))
y = F.reshape(x, (6,))
y.backward(retain_grad=True)
print(x.grad)

variable([[1 1 1]
          [1 1 1]])


In [14]:
x = np.random.rand(1, 2, 3)

y = x.reshape((2,3))
y = x.reshape([2,3])
y = x.reshape(2,3)

In [16]:
# likewise

x = Variable(np.random.randn(1,2,3))
y = x.reshape((2,3))
y = x.reshape(2, 3)

In [18]:
# transpose

x = np.array([[1,2,3],[4,5,6]])
y = np.transpose(x)
print(y)


[[1 4]
 [2 5]
 [3 6]]


In [20]:
class Transpose(Function):
    def forward(self, x):
        y = np.transpose(x)
        return y

    def backward(self, gy):
        gx = trnaspose(gy)
        return gx

def transpose(x):
    return Transpose()(x)

NameError: name 'Function' is not defined

In [22]:
x = Variable(np.array([[1,2,3],[4,5,6]]))
y = F.transpose(x)
y.backward()
print(x.grad)


variable([[1 1 1]
          [1 1 1]])
